# Limitação da quantidade de camadas por conta do tamanhos das imagens do dataset
# (imagens pequenas sofrem redução ao longo das camadas)
<architecture> ::= <layer> <layer> <layer> <layer>
					| <layer> <layer> <layer>
					| <layer> <layer>
<layer> ::= conv2D <output_filters> | max_pool
<output_filters> ::= 32 | 64 | 128