# Limitação da quantidade de camadas por conta do tamanhos das imagens do dataset
# (imagens pequenas sofrem redução ao longo das camadas)
<architecture> ::= <layer> <layer> <layer> <layer>
					| <layer> <layer> <layer>
					| <layer> <layer>
<layer> ::= <type>
<type> ::= max_pool | conv2D <output_filters>
<output_filters> ::= 32 | 64 | 128